# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# .github/dependabot.yml
version: 2
updates:
  # Bazel
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Bun
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Ruby (Bundler)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Python (Conda)
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Deno
  - package-ecosystem: "deno"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Docker containers
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Docker-Compose containers
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # .NET-SDK
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Git Submodule
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Java / Kotlin (Gradle)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Helm
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Julia
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Java (Maven)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Nix
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Node.js (npm, yarn, pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # .NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # OpenTofu
  - package-ecosystem: "opentofu"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Python (pip, Pipenv, Poetry)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Pre-commit
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Dart / Flutter (Pub)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Rust Toolchain
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Swift (SwiftPM)
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # UV
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
  # VC-PKG
  - package-ecosystem: "vcpkg"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
